version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Installing source NPM dependencies...
      - npm install -g typescript
      - npm install
      - aws codeartifact login --tool npm --repository helpmycase --domain helpmycase --domain-owner 460234074473
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - npm version 0.1.${CODEBUILD_BUILD_NUMBER}
      - npm publish