version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Installing source NPM dependencies...
      - npm install
      - aws codeartifact login --tool npm --repository worldwideandweb-storybook --domain worldwideandweb --domain-owner 460234074473
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - npm publish ./src/components