version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of build to codeartifact
      - aws codeartifact login --tool npm --repository worldwideandweb-storybook --domain worldwideandweb --domain-owner 460234074473
artifacts:
  files:
    - 'components/*'
  base-directory: src